name: Build

on:
  push:
    branches-ignore: [master, develop]
  pull_request:
    branches-ignore: [master, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Swift 5.8
      run: |
        wget -q https://download.swift.org/swift-5.8-release/ubuntu2204/swift-5.8-RELEASE-ubuntu22.04.tar.gz
        tar xzf swift-5.8-RELEASE-ubuntu22.04.tar.gz
        echo "$PWD/swift-5.8-RELEASE-ubuntu22.04/usr/bin" >> $GITHUB_PATH

    - name: Show Swift version
      run: swift --version

    - name: Show package dependencies
      run: swift package show-dependencies

    - name: Build with Publish
      run: swift run
      env:
        SWIFT_BACKTRACE: 1
