name: Build

on:
  push:
    branches-ignore: [master, develop]
  pull_request:
    branches-ignore: [master, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Show Swift version
      run: swift --version

    - name: Show package dependencies
      run: swift package show-dependencies

    - name: Build with Publish
      run: swift run
      env:
        SWIFT_BACKTRACE: 1
