name: Build

on:
  push:
    branches-ignore: [master, develop]
  pull_request:
    branches-ignore: [master, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy with Publish
      run: swift run
