name: Build

on:
  push:
    branches-ignore: [master, develop]
  pull_request:
    branches-ignore: [master, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: swift:5.7-focal

    steps:
    - uses: actions/checkout@v4

    - name: Show Swift version
      run: swift --version

    - name: Build project
      run: swift build