name: Build

on:
  push:
    branches-ignore: [master, develop]
  pull_request:
    branches-ignore: [master, develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Show Swift version
      run: swift --version

    - name: Show package dependencies
      run: swift package show-dependencies

    - name: Build with Publish
      run: swift run
      env:
        SWIFT_BACKTRACE: 1
