name: Test inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define environment'
        required: true
        type: choice
        options:
        - staging
        - demo
        - production 
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    if: inputs.environment == 'staging'
    steps:
      - name: Send greeting
        run: echo "${{ inputs.environment }}"
