name: Test inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define environment'
        default: 'staging'
        required: true
        type: string
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    if: inputs.environment == 'staging'
    steps:
      - name: Send greeting
        run: echo "${{ inputs.environment }}"
