name: Test inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define environment'
        default: 'staging'
        required: true
        type: string
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo "Input: ${{ inputs.environment }}"
